const folderInput = document.getElementById('game-folder');
const statusText = document.getElementById('status-text');
const startBtn = document.getElementById('start-btn');
const uiLayer = document.getElementById('ui-layer');
const gameFrame = document.getElementById('game-frame');
const closeBtn = document.getElementById('close-game-btn');

let swRegistration = null;

// Register Service Worker
async function registerSW() {
    if ('serviceWorker' in navigator) {
        try {
            swRegistration = await navigator.serviceWorker.register('sw.js', { scope: '/' });
            console.log('Service Worker registered with scope:', swRegistration.scope);
            
            // Wait for SW to be ready and active
            await navigator.serviceWorker.ready;
            
            // If the SW is waiting, we might need to skip waiting, but ideally handled in SW
        } catch (error) {
            console.error('Service Worker registration failed:', error);
            statusText.textContent = 'Tristemente el navegador no soporta la ejecución offline requerida.';
            statusText.style.color = '#ff6b6b';
        }
    } else {
        statusText.textContent = 'Service Workers no están soportados en este navegador.';
        statusText.style.color = '#ff6b6b';
    }
}

// Handle folder selection
folderInput.addEventListener('change', async (event) => {
    const files = event.target.files;
    
    if (!files || files.length === 0) {
        statusText.textContent = 'No se seleccionó ninguna carpeta.';
        return;
    }

    startBtn.classList.add('hidden');
    startBtn.disabled = true;
    statusText.textContent = 'Procesando archivos...';

    // Verify if it is an RPG Maker project (look for index.html at root level or near it)
    // webkitRelativePath format is "FolderName/path/to/file.ext"
    let hasIndex = false;
    let rootPath = "";

    // Find the root path by looking for index.html
    for (let i = 0; i < files.length; i++) {
        const file = files[i];
        if (file.name === 'index.html') {
            hasIndex = true;
            // Get the directory containing index.html
            const pathParts = file.webkitRelativePath.split('/');
            pathParts.pop(); // remove index.html
            rootPath = pathParts.join('/') + '/';
            if (rootPath === '/') rootPath = ''; // Edge case
            break;
        }
    }

    if (!hasIndex) {
        statusText.textContent = 'No se encontró el archivo index.html. Asegúrate de seleccionar la carpeta del juego exportado de RPG Maker.';
        statusText.style.color = '#ff6b6b';
        return;
    }

    // Build map of files taking rootPath into account
    // We want the virtual path to be relative to the index.html location
    const fileMap = {};
    for (let i = 0; i < files.length; i++) {
        const file = files[i];
        let relativePath = file.webkitRelativePath;
        if (rootPath && relativePath.startsWith(rootPath)) {
            relativePath = relativePath.substring(rootPath.length);
        } else if (!rootPath) {
            // If the rootPath is empty, maybe the first folder is the root.
            const parts = relativePath.split('/');
            if (parts.length > 1) {
                parts.shift(); // remove the root folder name generated by webkitdirectory
                relativePath = parts.join('/');
            }
        }
        
        // Use lowercase for path keys to avoid case mismatch issues common in case-insensitive OS ports (like from Windows to iOS)
        fileMap[relativePath] = file;
    }

    statusText.textContent = `Preparando ${Object.keys(fileMap).length} archivos...`;

    // Wait for the active service worker
    const activeSW = navigator.serviceWorker.controller || (swRegistration && swRegistration.active);
    
    if (!activeSW) {
        statusText.textContent = 'Service Worker no está listo. Recarga la página y vuelve a intentar.';
        return;
    }

    // Send files to the Service Worker
    try {
        await sendMessageToSW({
            type: 'LOAD_GAME_FILES',
            files: fileMap
        });
        
        statusText.textContent = '¡Juego listo para jugar!';
        statusText.style.color = '#51cf66';
        startBtn.classList.remove('hidden');
        startBtn.disabled = false;
    } catch (err) {
        console.error('Error sending files to SW:', err);
        statusText.textContent = 'Hubo un error al preparar los archivos.';
        statusText.style.color = '#ff6b6b';
    }
});

// Start button
startBtn.addEventListener('click', () => {
    // Hide UI
    uiLayer.classList.remove('active');
    
    // Show Iframe
    gameFrame.classList.remove('hidden');
    closeBtn.classList.remove('hidden');
    
    // Load virtual path where the SW serves the files
    // Use a unique query string to avoid caching issues on iframe reload
    gameFrame.src = `/rpgm-game/index.html?t=${Date.now()}`;
    
    // Focus the game after loading to allow keyboard/touch input
    setTimeout(() => {
        gameFrame.focus();
    }, 500);
});

// Close game button
closeBtn.addEventListener('click', () => {
    gameFrame.classList.add('hidden');
    closeBtn.classList.add('hidden');
    uiLayer.classList.add('active');
    gameFrame.src = 'about:blank'; // unload game
});

// Utility to send messages to SW and wait for response
function sendMessageToSW(message) {
    return new Promise((resolve, reject) => {
        const messageChannel = new MessageChannel();
        messageChannel.port1.onmessage = (event) => {
            if (event.data.error) {
                reject(event.data.error);
            } else {
                resolve(event.data);
            }
        };

        const activeSW = navigator.serviceWorker.controller || swRegistration.active;
        if (activeSW) {
            activeSW.postMessage(message, [messageChannel.port2]);
        } else {
            reject('No active Service Worker found');
        }
    });
}

// Initialize
requestAnimationFrame(() => {
    registerSW();
});
